import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./Components/Sidebar";

import "./Styles/usersSetting.css";
import "./Styles/popup.css";
import "./Styles/adminPanel.css";
import "./Styles/login.css";
import "./Styles/order.css";
import "./Styles/homepage.css";
import "./Styles/main.css"
import AuthProvider from "./context/AuthProvider";



const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Sidebar></Sidebar>{children}
        </AuthProvider>
      </body>
    </html>
  );
  
}
